apiVersion: v1
kind: Pod
metadata:
  name: ng1
  namespace: default
  labels:
    app: ng1
spec:
  initContainers:
    - name: init-copy-content
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "<h1>Hello World from $HOSTNAME!</h1>" > /tmp/index.html
          cp /tmp/index.html /usr/share/nginx/html/
      volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html

  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      resources:
        requests:
          cpu: 1
          memory: 500Mi
        limits:
          cpu: 1
          memory: 500Mi

  volumes:
    - name: web-content
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ng1
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ng1